[WIP] Initial workflow setup for SNAX repo
KULeuven-MICAS/snax-dev pull request #1
Opened 2023-08-14 16:03 UTC by rgantonio

This PR contains a full workflow from RTL, to a cocotb test (in container), and a CI that tests it out. More details include:

1. A simple counter RTL was placed for the sake of testing the entire workflow. It will be taken out later once we put in a bigger system to test.
2. A simple cocotb test to check the first 5 outputs of the counter was included.
3. There are instructions in the main README to indicate the requirements for making the test run.
4. README instructions under util/container tell the user where and how to run the tests. (Will be moved under /tests if needed)
5. CI that pulls the pre-built container. Verilator and cocotb work in the container.
6. End-to-end from RTL, to cocotb test, to CI are working.

@JosseVanDelm please check this out and provide feedback if there are necessary changes :)

Set as draft PR for now.

2023-08-14 17:13 UTC, JosseVanDelm requested changes
Hi Ryan,

Thanks, this looks great overall!
However, you seem to add a lot of IMHO pretty obvious comments.
While it is always better to have too many comments than too few, I think some of the comments are not very informative and can be left out.

We should aim to setup `pyright` and `black` in the next PR's (I can do this tomorrow)

2023-08-14 17:13 UTC, JosseVanDelm commented on tests/cocotb/test_counter.py
> +    # Wait 2 cycles to reset
Why not just 1 cycle?

2023-08-14 17:13 UTC, JosseVanDelm commented on tests/cocotb/test_counter.py
> +# Parametrization
These comments seem pretty meaningless

2023-08-16 09:44 UTC, rgantonio commented on util/container/Dockerfile
> +#---------------------
Done!

2023-08-16 09:44 UTC, rgantonio commented on util/container/Dockerfile
> +#---------------------
Done!

2023-08-16 09:47 UTC, rgantonio commented on util/container/Dockerfile
> +#---------------------
Done!

2023-08-16 09:48 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +random.seed(RANDOM_SEED)
Oh I forgot to take it out, but the original intent (from the HWPE stream before) was indeed for randomization. I was thinking it was more proper to do regression or tests when we know the random seed used. So we can replicate the error if there was an error.

2023-08-16 09:49 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +def test_hwpe_stream_merge(parameters):
Oops haha

2023-08-16 09:55 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +# -----------------------------------
I will move those that are part actually part of test_counter to the actual function. But I will leave the CHECK_COUNT and COUNTER_WIDTH at the top. 

The original intent of all these variables was to make it easier for other users to configure the variables. Like they are all at the top of the code. For example, if I want to move from "verilator" to "modelsim" I could always just modify the top variables without having to scroll down below. Is that fine?

2023-08-16 09:55 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +)
This is indeed future proofing. This was based on Gui's example so I re-used it here.

2023-08-16 09:56 UTC, rgantonio commented on util/container/Dockerfile
> +#---------------------
Done!

2023-08-16 09:56 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +random.seed(RANDOM_SEED)
I will take this out in the next commit wait.

2023-08-16 11:54 UTC, JosseVanDelm commented on tests/cocotb/test_counter.py
> +# -----------------------------------
@rgantonio I get it, but we should not expect users to use this.
All tests should be runned with a single simple pytest invocation.
What we could do instead is the following:
https://github.com/KULeuven-MICAS/htvm/blob/main/diana/byoc/conftest.py

That way you write your python tests as:
```python
def my_test_on_any_simulator(simulator):
```
And you would invoke pytest with:
```
pytest --simulator=verilator
```

2023-08-16 12:40 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +# -----------------------------------
Let's do this in next PR so I can also practice doing the review!

2023-08-16 12:45 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +# -----------------------------------
Done!

2023-08-16 12:45 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +# -----------------------------------
Done!

2023-08-16 12:45 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +# -----------------------------------
Done!

2023-08-16 12:45 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +    # Wait 2 cycles to reset
Done!

2023-08-16 12:45 UTC, rgantonio commented on tests/cocotb/test_counter.py
> +# Parametrization
Done!

2023-08-16 14:29 UTC, JosseVanDelm approved these changes
Beautiful! Feel free to merge @rgantonio!

2023-08-16 15:05 UTC, rgantonio commented
Thank you! @JosseVanDelm! 😄

2023-08-16 15:06 UTC, merged